name: Pipeline PR push

on:
  pull_request:

jobs:
  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      testProjects: ${{ steps.set-matrix.outputs.testProjects }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Test Projects
        id: set-matrix
        run: |
          projects=$(find tests -name '*.csproj' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "Found test projects: $projects"
          echo "testProjects=$projects" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    outputs:
      os: ${{ matrix.os }}
    name: build (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore --locked-mode
      - run: dotnet clean --verbosity quiet
      - run: dotnet build --verbosity quiet /property:WarningLevel=0

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            **/bin/
            **/obj/

  build-and-test:
    needs: [discover-tests, build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        testProject: ${{ fromJson(needs.discover-tests.outputs.testProjects) }}
    name: build-and-test (${{ matrix.os }} | ${{ matrix.testProject }})
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}

      - name: Run Test Project
        run: |
          mkdir -p TestResults
          project="${{ matrix.testProject }}"
          safe_name=$(basename "$project" .csproj)
          dotnet test "$project" --no-restore --no-build --logger "trx;LogFileName=$safe_name.trx" --results-directory ./TestResults
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ hashFiles(matrix.testProject) }}
          path: ./TestResults/

      - name: Show Failed Tests
        if: failure()
        run: echo "Some tests failed. Check uploaded artifacts for detailed logs."
